name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up .NET
      uses: actions/setup-node@v3
      with:
        dotnet-version: '5.0'


    - name: RestoreCatalog
      run: |
        cd Shop.Catalog/src/Shop.Catalog.Service
        dotnet restore Shop.Catalog.Service.csproj

    - name: BuildCatalog
      run: |
        cd Shop.Catalog/src/Shop.Catalog.Service
        dotnet build Shop.Catalog.Service.csproj

    - name: PublishCatalog
      run: |
        cd Shop.Catalog/src/Shop.Catalog.Service
        dotnet publish Shop.Catalog.Service.csproj

    - name: RestoreInventory
      run: |
        cd Shop.Catalog/src/Shop.Inventory.Service
        dotnet restore Shop.Inventory.Service.csproj

    - name: BuildInventory
      run: |
        cd Shop.Catalog/src/Shop.Inventory.Service
        dotnet build Shop.Inventory.Service.csproj

    - name: PublishInventory
      run: |
        cd Shop.Catalog/src/Shop.Inventory.Service
        dotnet publish Shop.Inventory.Service.csproj

